time_model_file_name: grouped_data.csv
drop_columns:
- cluster
- transactions
group_columns:
- date
sum_columns:
- onpromotion
- holiday_type
- sales
- family
- store_type
- store_nbr
mean_columns:
- oil_price
label_encode:
- holiday_type
- family
- store_type
target_column:
- sales
exog_columns:
- onpromotion
- holiday_type
- store_type
- store_nbr

